export const APP_PERMISSIONS = [
  'TENANT_MANAGE',
  'PRODUCTS_MANAGE',
  'SALES_MANAGE',
  'SALES_VOID',
  'SALES_DISCOUNT',
  'SALE_REPRINT',
  'CASH_REGISTER_OPEN',
  'CASH_REGISTER_CLOSE',
  'CASH_REGISTER_MOVE',
  'ACCESS_MANAGE',
  'AUDIT_VIEW',
  'AUDIT_EXPORT',
  'SUPPLIERS_MANAGE',
  'PURCHASE_ORDERS_MANAGE',
  'PURCHASE_ORDERS_APPROVE',
  'PURCHASE_RECEIPTS_OVERAGE',
  'INVENTORY_VIEW',
  'INVENTORY_ADJUST',
  'INVENTORY_TRANSFER',
  'INVENTORY_COUNT',
  'INVENTORY_APPROVE',
] as const;

export type AppPermission = (typeof APP_PERMISSIONS)[number];

export const INVENTORY_PERMISSIONS = [
  'INVENTORY_VIEW',
  'INVENTORY_ADJUST',
  'INVENTORY_TRANSFER',
  'INVENTORY_COUNT',
  'INVENTORY_APPROVE',
] as const satisfies readonly AppPermission[];

export const OPERATIONAL_PERMISSIONS = [
  ...INVENTORY_PERMISSIONS,
  'SALES_MANAGE',
  'SALES_VOID',
  'SALES_DISCOUNT',
  'SALE_REPRINT',
  'CASH_REGISTER_OPEN',
  'CASH_REGISTER_CLOSE',
  'CASH_REGISTER_MOVE',
  'AUDIT_VIEW',
  'AUDIT_EXPORT',
  'SUPPLIERS_MANAGE',
  'PURCHASE_ORDERS_MANAGE',
  'PURCHASE_ORDERS_APPROVE',
  'PURCHASE_RECEIPTS_OVERAGE',
] as const satisfies readonly AppPermission[];
